name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          cmake ninja-build \
          libgl1-mesa-dev libglu1-mesa-dev \
          libx11-dev libxrandr-dev libxinerama-dev \
          libxcursor-dev libxi-dev

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_RAYLIB=OFF

      - name: Build
        run: cmake --build build

      - name: Stage release
        run: |
          mkdir release
          cp build/game release/
          cp -r assets release/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-linux
          path: release/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: choco install ninja

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure (using MSVC)
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_RAYLIB=OFF -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl

      - name: Build
        run: cmake --build build

      - name: Stage release
        run: |
          mkdir release
          copy build\game.exe release\
          xcopy /E /I assets release\assets
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-windows
          path: release/
